#!/bin/bash

# Trading Bot Help Script
# Displays all available management commands

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo "================================================================================"
echo -e "${GREEN}                   TRADING BOT MANAGEMENT COMMANDS${NC}"
echo "================================================================================"
echo ""

echo -e "${BLUE}📦 BOT SERVICE MANAGEMENT${NC}"
echo "--------------------------------------------------------------------------------"
echo -e "${CYAN}sudo systemctl start trading-bot${NC}"
echo "   Start the trading bot service"
echo ""
echo -e "${CYAN}sudo systemctl stop trading-bot${NC}"
echo "   Stop the trading bot service"
echo ""
echo -e "${CYAN}sudo systemctl restart trading-bot${NC}"
echo "   Restart the trading bot service"
echo ""
echo -e "${CYAN}sudo systemctl status trading-bot${NC}"
echo "   Check the current status of the bot"
echo ""
echo -e "${CYAN}sudo systemctl enable trading-bot${NC}"
echo "   Enable bot to start automatically on system boot"
echo ""
echo -e "${CYAN}sudo systemctl disable trading-bot${NC}"
echo "   Disable bot from starting automatically on system boot"
echo ""

echo -e "${BLUE}📋 LOGS & MONITORING${NC}"
echo "--------------------------------------------------------------------------------"
echo -e "${CYAN}sudo journalctl -u trading-bot -f${NC}"
echo "   View live logs (press Ctrl+C to exit)"
echo ""
echo -e "${CYAN}sudo journalctl -u trading-bot --since today${NC}"
echo "   View logs from today"
echo ""
echo -e "${CYAN}sudo journalctl -u trading-bot --since '1 hour ago'${NC}"
echo "   View logs from the last hour"
echo ""
echo -e "${CYAN}sudo journalctl -u trading-bot -n 100${NC}"
echo "   View last 100 log lines"
echo ""
echo -e "${CYAN}sudo journalctl -u trading-bot | grep -i 'error\|warning'${NC}"
echo "   Filter logs for errors and warnings"
echo ""
echo -e "${CYAN}sudo journalctl -u trading-bot | grep -i 'position\|pnl\|close'${NC}"
echo "   Filter logs for position-related events"
echo ""

echo -e "${BLUE}🔄 UPDATE & DEPLOYMENT${NC}"
echo "--------------------------------------------------------------------------------"
echo -e "${CYAN}sudo ~/trading-bot-setup/life_is_a_joke/scripts/update_bot.sh${NC}"
echo "   Update bot to latest version (recommended)"
echo ""
echo -e "${CYAN}cd ~/trading-bot-setup/life_is_a_joke && git pull${NC}"
echo "   Pull latest changes from repository"
echo ""
echo -e "${CYAN}cd ~/trading-bot-setup/life_is_a_joke && git status${NC}"
echo "   Check repository status and changes"
echo ""
echo -e "${CYAN}cd ~/trading-bot-setup/life_is_a_joke && git log --oneline -10${NC}"
echo "   View last 10 commits"
echo ""

echo -e "${BLUE}🔍 DIAGNOSTICS & DEBUGGING${NC}"
echo "--------------------------------------------------------------------------------"
echo -e "${CYAN}python3 ~/trading-bot-setup/life_is_a_joke/scripts/test_ai_system.py${NC}"
echo "   🤖 Test AI system (commentary, adaptive tactics, ML analyzers)"
echo ""
echo -e "${CYAN}python3 ~/trading-bot-setup/life_is_a_joke/scripts/analyze_trades.py${NC}"
echo "   📊 Run full ML performance analysis"
echo ""
echo -e "${CYAN}python3 ~/trading-bot-setup/life_is_a_joke/scripts/diagnose_positions.py${NC}"
echo "   Run position diagnostics script"
echo ""
echo -e "${CYAN}sqlite3 /var/lib/trading-bot/trading_bot.db 'SELECT * FROM positions;'${NC}"
echo "   Query all positions from database"
echo ""
echo -e "${CYAN}sqlite3 /var/lib/trading-bot/trading_bot.db 'SELECT * FROM positions WHERE status=\"open\";'${NC}"
echo "   Query only open positions"
echo ""
echo -e "${CYAN}sqlite3 /var/lib/trading-bot/trading_bot.db 'SELECT * FROM positions WHERE status=\"closed\" ORDER BY closed_at DESC LIMIT 10;'${NC}"
echo "   View last 10 closed positions"
echo ""
echo -e "${CYAN}sqlite3 /var/lib/trading-bot/trading_bot.db 'SELECT symbol, COUNT(*), SUM(pnl) FROM positions WHERE status=\"closed\" GROUP BY symbol;'${NC}"
echo "   View P&L summary by symbol"
echo ""

echo -e "${BLUE}⚙️  CONFIGURATION${NC}"
echo "--------------------------------------------------------------------------------"
echo -e "${CYAN}nano /etc/trading-bot/.env${NC}"
echo "   Edit bot configuration (use Ctrl+X to save and exit)"
echo ""
echo -e "${CYAN}cat /etc/trading-bot/.env${NC}"
echo "   View current configuration"
echo ""
echo -e "${CYAN}cat /etc/trading-bot/.env | grep MAX_${NC}"
echo "   View position and trade limits"
echo ""
echo -e "${CYAN}cat /etc/trading-bot/.env | grep CONFIDENCE${NC}"
echo "   View confidence-based sizing settings"
echo ""

echo -e "${BLUE}📊 DATABASE MANAGEMENT${NC}"
echo "--------------------------------------------------------------------------------"
echo -e "${CYAN}sqlite3 /var/lib/trading-bot/trading_bot.db${NC}"
echo "   Open database interactive shell (type .exit to quit)"
echo ""
echo -e "${CYAN}sqlite3 /var/lib/trading-bot/trading_bot.db '.schema'${NC}"
echo "   View database schema"
echo ""
echo -e "${CYAN}sqlite3 /var/lib/trading-bot/trading_bot.db 'PRAGMA table_info(positions);'${NC}"
echo "   View positions table structure"
echo ""
echo -e "${CYAN}sqlite3 /var/lib/trading-bot/trading_bot.db '.backup /tmp/trading_bot_backup.db'${NC}"
echo "   Create database backup"
echo ""
echo -e "${CYAN}python3 ~/trading-bot-setup/life_is_a_joke/scripts/reset_daily_limit.py --status${NC}"
echo "   Check current daily trade limit status"
echo ""
echo -e "${CYAN}python3 ~/trading-bot-setup/life_is_a_joke/scripts/reset_daily_limit.py${NC}"
echo "   Reset daily trade counter (allows more trading today)"
echo ""

echo -e "${BLUE}🧹 MAINTENANCE${NC}"
echo "--------------------------------------------------------------------------------"
echo -e "${CYAN}sudo find /opt/trading-bot -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null${NC}"
echo "   Clean Python cache files"
echo ""
echo -e "${CYAN}sudo chown -R tradingbot:tradingbot /opt/trading-bot${NC}"
echo "   Fix file ownership"
echo ""
echo -e "${CYAN}sudo chmod +x ~/trading-bot-setup/life_is_a_joke/scripts/*.sh${NC}"
echo "   Make all scripts executable"
echo ""
echo -e "${CYAN}df -h /var/lib/trading-bot${NC}"
echo "   Check disk space usage"
echo ""

echo -e "${BLUE}🆘 TROUBLESHOOTING${NC}"
echo "--------------------------------------------------------------------------------"
echo -e "${CYAN}sudo systemctl daemon-reload${NC}"
echo "   Reload systemd configuration if service file changed"
echo ""
echo -e "${CYAN}sudo systemctl reset-failed trading-bot${NC}"
echo "   Reset failed state if service won't start"
echo ""
echo -e "${CYAN}journalctl -xe${NC}"
echo "   View system logs for recent errors"
echo ""
echo -e "${CYAN}ps aux | grep trading${NC}"
echo "   Check if bot process is running"
echo ""

echo -e "${BLUE}💡 QUICK RECIPES${NC}"
echo "--------------------------------------------------------------------------------"
echo -e "${YELLOW}Full update and restart:${NC}"
echo "   sudo ~/trading-bot-setup/life_is_a_joke/scripts/update_bot.sh"
echo ""
echo -e "${YELLOW}Test AI system:${NC}"
echo "   python3 ~/trading-bot-setup/life_is_a_joke/scripts/test_ai_system.py"
echo ""
echo -e "${YELLOW}View today's P&L:${NC}"
echo "   sqlite3 /var/lib/trading-bot/trading_bot.db \"SELECT COALESCE(SUM(pnl), 0) FROM positions WHERE status='closed' AND DATE(closed_at) = DATE('now', 'localtime');\""
echo ""
echo -e "${YELLOW}Count open positions:${NC}"
echo "   sqlite3 /var/lib/trading-bot/trading_bot.db \"SELECT COUNT(*) FROM positions WHERE status='open';\""
echo ""
echo -e "${YELLOW}Watch live trading activity:${NC}"
echo "   sudo journalctl -u trading-bot -f | grep -i 'signal\\|position\\|buy\\|sell'"
echo ""
echo -e "${YELLOW}Watch AI activity:${NC}"
echo "   sudo journalctl -u trading-bot -f | grep -i 'AI\\|adaptive\\|commentary'"
echo ""
echo -e "${YELLOW}Emergency stop:${NC}"
echo "   sudo systemctl stop trading-bot"
echo ""

echo "================================================================================"
echo -e "${GREEN}For more help, visit the repository or check the documentation${NC}"
echo "================================================================================"
echo ""
